[theme]
base = "dark"
primaryColor = "#E5322D"
backgroundColor = "#0b0b12"
secondaryBackgroundColor = "#121220"
textColor = "#eaeaf2"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
