[theme]
base = "dark"
primaryColor = "#E5322D"
backgroundColor = "#0b0b12"
secondaryBackgroundColor = "#121220"
textColor = "#eaeaf2"
font = "sans serif"

[server]
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true
headless = true
websocketPingInterval = 30
websocketPingTimeout = 120

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501
